#!/bin/bash
# Generate ~/Applications/Metsuke.app idempotently.
#
# A bundle launched from Dock or Spotlight gets a minimal environment: no shell
# PATH, no uv, no workspace variables. Every path the launcher uses is therefore
# resolved here, at install time, and baked in as an absolute path.
set -euo pipefail
umask 022
repo=$(cd "$(dirname "$0")/.." && pwd)
metsuke_bin="$repo/.venv/bin/metsuke"
[ -x "$metsuke_bin" ] || { echo "missing $metsuke_bin; run: uv sync --frozen" >&2; exit 1; }

export METSUKE_CONFIG_OVERRIDE=1
. "$repo/scripts/load-config.sh"
unset METSUKE_CONFIG_OVERRIDE
data_home=${METSUKE_HOME:-"$HOME/.metsuke"}
log_path="$data_home/logs/metsuke-app.log"

apps_dir=${METSUKE_APPS_DIR:-"$HOME/Applications"}
app="$apps_dir/Metsuke.app"
contents="$app/Contents"
macos="$contents/MacOS"
launcher="$macos/Metsuke"
plist="$contents/Info.plist"

mkdir -p "$macos"

# Written without a timestamp or any other varying value so that re-running the
# installer converges instead of rewriting the bundle every time.
plist_body=$(cat <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>Metsuke</string>
	<key>CFBundleIdentifier</key>
	<string>com.metsuke.app</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Metsuke</string>
	<key>CFBundleDisplayName</key>
	<string>Metsuke</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSMinimumSystemVersion</key>
	<string>13.0</string>
	<key>NSHighResolutionCapable</key>
	<true/>
</dict>
</plist>
PLIST
)

launcher_body=$(cat <<LAUNCHER
#!/bin/bash
# metsuke app launcher v1 (generated by scripts/install-app.sh; edits are overwritten)
# metsuke-target: $metsuke_bin
# Dock and Spotlight provide no PATH and no uv, so the venv entrypoint is called
# by absolute path. Output goes to a file because there is no terminal to see.
set -u
mkdir -p "$data_home/logs" 2>/dev/null || true
exec >>"$log_path" 2>&1
exec "$metsuke_bin" dashboard open
LAUNCHER
)

install_file() {
  target=$1
  body=$2
  mode=$3
  if [ -f "$target" ] && [ "$(cat "$target")" = "$body" ]; then
    current_mode=$(stat -f '%Lp' "$target" 2>/dev/null || echo "")
    if [ "$current_mode" = "$mode" ]; then
      echo "unchanged: $target"
      return 0
    fi
  fi
  tmp="$target.tmp-$$"
  printf '%s\n' "$body" >"$tmp"
  chmod "$mode" "$tmp"
  mv -f "$tmp" "$target"
  echo "installed: $target"
}

install_file "$plist" "$plist_body" 644
install_file "$launcher" "$launcher_body" 755

# A freshly generated or regenerated bundle stays invisible to Spotlight until
# LaunchServices re-reads it. Absence of the tool is not an installation failure.
lsregister=${METSUKE_LSREGISTER:-/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister}
if [ -x "$lsregister" ]; then
  "$lsregister" -f "$app" >/dev/null 2>&1 || echo "warning: lsregister failed; Spotlight may not see $app yet" >&2
else
  echo "warning: lsregister not found; Spotlight may not see $app until the next login" >&2
fi
echo "app: $app"
